<?php
/**
* @file
* A description of what your module does.
*/

function hook_block_info() {
    // This example comes from node.module.
    $blocks['parts_select'] = array(
        'info' => t('Parts Selection'),
        'cache' => DRUPAL_NO_CACHE
    );

    $blocks['recent'] = array(
        'info' => t('Recent content'),
        // DRUPAL_CACHE_PER_ROLE will be assumed.
    );

    return $blocks;
}