<?php
/**
* @file
* A description of what your module does.
*/

function my_news_menu() {
    $items = array();
    $items['mynews'] = array(
        'title' => t('My News'),
        'page callback' => 'my_news_list',
        'access arguments' => array('access content'),
    );
    return $items;
}

/**
 * @return string
 */
function my_news_list(){

    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'news')
        ->propertyCondition('status', 'NODE_PUBLISHED')
        ->propertyOrderBy('created', 'DESC')
        ->range(0, 10);

    $result = $query->execute();

    if (isset($result['node'])) {
        $news_items_nids = array_keys($result['node']);
        $news_items = entity_load('node', $news_items_nids);
    }

    $output = "<ul>\n";
    foreach($news_items as $news_item) {
        $snippet = "<li>\n";
        $snippet .= "<h2>".t($news_item->title)."</h2>\n";
        $snippet .= "<p>".t(substr($news_item->body['und'][0]['value'],0, 600))."</p>\n";
        $snippet .= "</li>\n";
        $output .= $snippet;
    }
    $output .= "</ul>\n";

    return $output;
}