<?php
/**
* @file
* A description of what your module does.
*/
/**
 * Implements hook_block_info().
 */
function myblock_block_info() {
    $blocks = array();
    $blocks['my_block'] = array(
        'info' => t('My Custom Block'),
        'cache' => DRUPAL_NO_CACHE,
    );

    return $blocks;
}


/**
 * Implement db query
 */



/**
 * Implements hook_block_view().
 * Check output
 */
function myblock_block_view($delta = '') {
    $block = array();
    switch ($delta) {
        case 'my_block':
            $block['subject'] = t('Block Title');
            $block['content'] = t('Hello World!');
            break;
    }
    return $block;
}